

title: IntroIT
email: 
description: ""
keywords: ""
skills: ""
meta_author: 

markdown: kramdown
permalink: pretty

include:
  - src/*.md

#for posts
defaults:
  - scope:
      path: "src"
      type: "posts"
    values:
      permalink: ""
      post: true
