

title: IntroIT
email: 
description: ""
keywords: ""
skills: ""
meta_author: 

markdown: kramdown
permalink: pretty


#for posts
defaults:
  - scope:
      path: "src"
      type: "posts"
    values:
      permalink: ""